on:
  - push
  - pull_request

env:
  NODE_VERSION: 20

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: pnpm install
      - name: Run lint
        run: pnpm lint

  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    needs: [lint]
    strategy:
      fail-fast: false
      matrix:
        # TODO: Fix tests for Svelte 5
        # svelte-version: ['4.2.12', '5.0.0']
        svelte-version: ['4.2.12']

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: pnpm install
      - name: Install Svelte version ${{ matrix.svelte-version }}
        run: pnpm add -D svelte@${{ matrix.svelte-version }}
      - name: Install playwright browsers
        run: pnpm exec playwright install
      - name: Run tests
        run: pnpm test:ct

  tests_unit:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: [lint]
    strategy:
      fail-fast: false
      matrix:
        # TODO: Fix tests for Svelte 5
        # svelte-version: ['4.2.12', '5.0.0']
        svelte-version: ['4.2.12']

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: pnpm install
      - name: Install Svelte version ${{ matrix.svelte-version }}
        run: pnpm add -D svelte@${{ matrix.svelte-version }}
      - name: Run unit tests
        run: pnpm test:unit
