on:
  - push
  - pull_request

env:
  NODE_VERSION: 20

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: pnpm install
      - run: pnpm lint

  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: pnpm install
      - run: pnpm test:visual

  tests_unit:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: pnpm install
      - run: pnpm test:unit
