on:
  - push
  - pull_request

env:
  PNPM_VERSION: 8.3.1

jobs:
  cache-deps:
    name: Cache PNPM install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install Dependencies
        run: pnpm install

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [cache-deps]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Run lint
        run: pnpm lint

  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Install playwright browsers
        run: pnpm exec playwright install
      - name: Run tests
        run: pnpm test:ct

  tests_unit:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Run unit tests
        run: pnpm test:unit
