name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 20

      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm -F svelte-promise-modals build
        env:
          PUBLIC_BASE_URL: https://svelte-promise-modals.com

      - name: Set publishing config
        run: cd svelte-promise-modals && pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: publish to npm
        run: cd svelte-promise-modals && pnpm publish
